config/routes.rb
Rails.application.routes.draw do
  get 'pages/info'

  root :to => redirect('/ideas')
  get    '/ideas'           => 'ideas#index'
get '/ideas/info'           =>'pages#info'
  get    '/ideas/new'       => 'ideas#new', as: 'new_idea'
  get    '/ideas/:id/edit'  => 'ideas#edit', as: 'edit_idea'
  get    '/ideas/:id'       => 'ideas#show', as: 'idea'

  post   '/ideas'           => 'ideas#create'
  patch  '/ideas/:id'       => 'ideas#update'
  put    '/ideas/:id'       => 'ideas#update'

  delete '/ideas/:id'       => 'ideas#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
  mount_uploader :picture, PictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  def index
    @ideas = Idea.all
    render 'index'
  end
  def show
    @idea = Idea.find(params[:id])
    render 'show'
  end
  def new
    @idea = Idea.new
    render 'new'
  end
  def edit
    @idea = Idea.find(params[:id])
    render 'edit'
  end
  def create
    @idea = Idea.new(idea_params)
    if @idea.save
      redirect_to @idea, notice: 'Idea was successfully created.'
    else
      render action: 'new'
    end
  end
  def update
    @idea = Idea.find(params[:id])
    if @idea.update(idea_params)
      redirect_to @idea, notice: 'Idea was successfully updated.'
    else
      render action: 'edit'
    end
  end
  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy
    redirect_to ideas_url, notice: 'Idea was successfully destroyed.'
  end
  private
  # Only allow a trusted parameter "white list" through.
  def idea_params
    params.require(:idea).permit(:name, :description, :picture)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ideas/_form.html.erb
<%= form_with(model: idea, local: true) do |form| %>
  <% if idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :idea_name, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :idea_description, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture, id: :idea_picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing Idea</h1>

<%= render 'form', idea: @idea %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ideas</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.name %></td>
        <td><%= idea.description %></td>
        <td><%= image_tag idea.picture_url, class: 'img-circle' if idea.picture? %></td>
        <td>
          <%= link_to idea, class: 'btn btn-default' do %>
          <span class="glyphicon glyphicon-search"></span>
          show
          <% end %>
        </td>
        <td>
          <%= link_to edit_idea_path(idea), class: 'btn btn-default' do %>
            <span class="glyphicon glyphicon-pencil"></span>
            Edit
          <% end %>
        </td>
        <td>
  <%= link_to idea, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do %>
    <span class="glyphicon glyphicon-remove"></span>
    Destroy
  <% end %>
</td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_idea_path, class: 'btn btn-primary btn-lg' do %>
  <span class="glyphicon glyphicon-plus"></span>
  New Idea
<% end %>

app/views/ideas/new.html.erb
<h1>New Idea</h1>

<%= render 'form', idea: @idea %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<% if notice %>
  <p id="notice" class="alert alert-success">
    <%= notice %>
  </p>
<% end %>

<p>
  <strong>Name:</strong>
  <%= @idea.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @idea.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@idea.picture_url) if @idea.picture.present? %>
</p>

<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railsgirls</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head><link href='http://fonts.googleapis.com/css?family=Arvo:400,700' rel='stylesheet' type='text/css'>

  <body>
    <div class='container'>
      <%= yield %>
    </div>
    <footer>
      <div class='container'>
        Rails Girls 2016
      </div>
    </footer>
  </body>
  <nav class='navbar navbar-default navbar-fixed-top' role='navigation'>
    <div class='container'>
      <div class='navbar-header'>
        <a class='navbar-brand' href='/'>The Idea app</a>
        <a class='navbar-brand' href='/ideas/info'>Info page</a>
      </div>
      <ul class='nav navbar-nav'>
      </li>
    </ul>
  </div>
</nav>
</html>

app/views/pages/info.html.erb
<h1>Code weekend</h1>
<h2>This rail has been great!</h2>
<p>Thank you!</p>